### ISSUE TITLE
Implicit cast operator does not execute validation

### ISSUE THREAD

**Issue by Peter-B-** [SteveDunn/Vogen#722] opened 2024-12-12 09:30 UTC
### Describe the bug

Hello and thanks for the great library. 

Implicit cast operator does not execute the `Validate()` method.

I'm actually not sure if this is a bug or desired behavior - it might be similar to #639.

If implicit operators should execute validation, I can create a PR for this.

Thank you
Peter

### Steps to reproduce

1. Create a value object with a `Validate` method and implicit cast operator
    ```csharp
    [ValueObject<string>(fromPrimitiveCasting: CastOperator.Implicit)]
    public partial class ImplicitId
    {
        public static Validation Validate(string value)
        {
            return string.IsNullOrWhiteSpace(value) ? Validation.Invalid("Must not be empty or whitespace") : Validation.Ok;
        }
    }
    ```

2. Create an instance using implicit cast with an invalid imput:
    ```csharp
    ImplicitId id = " ";
    ```

### Expected behaviour

An `ValueObjectValidationException` is thrown
> Vogen.ValueObjectValidationException: Must not be empty or whitespace

#### Observed bahaviour
An `ImplicitId` object is created with an invalid `Value`.

#### Note
An explicit operator will do validation.

**Comment by SteveDunn** [comment] 2024-12-12 18:12
Hi @Peter-B- thanks for the feedback. This is by design. implicit casts should never throw an exception. I've [documented it here](https://stevedunn.github.io/Vogen/faq.html#why-are-there-by-default-no-implicit-conversions-to-and-from-the-primitive-types-that-are-being-wrapped). I understand that documentation is rather difficult to find as it's buried deep in the FAQ section!

I'll close this for now, but if you feel that it's wrong or anything could be clearer, please let me know!

**Closed by SteveDunn** 2024-12-12 18:12 UTC
Labels: bug

**Comment by Peter-B-** [comment] 2024-12-13 11:08
Thanks for your response and for pointing me to the docs. I didn't know that about implicit casts.

I took this as an opportunity to remove all implicit casts and I'm quite happy with the result anyway.
